name: 'setup-gokcat'
description: 'Download and install the latest gokcat binary with caching support.'
author: 'philipparndt'
inputs:
  version:
    description: 'Version of gokcat to install. If not specified, the latest version will be used.'
    required: true
    default: 'v8.0.1'
outputs:
  gokcat-path:
    description: 'Path to the installed gokcat binary.'
runs:
  using: 'node12'
  main: 'action/dist/index.js'
