name: Setup Action

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Setup Action
        runs-on: ubuntu-latest
        steps:
            - name: Setup gokcat
              uses: philipparndt/gokcat@feat/ghe

            - name: Run gokcat
              run: |
                echo "Running gokcat to verify setup..."
                file /opt/hostedtoolcache/gokcat/0.7.2/x64/gokcat
                gokcat --help
                echo "gokcat setup completed successfully."
